- name: Install Docker on Reth Node Server
  hosts: all
  become: true
  tasks:
    - name: Remove old Docker packages
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - podman-docker
          - containerd
          - runc
        state: absent
        purge: true
        update_cache: true

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: true

    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ ansible_architecture | regex_replace('^(aarch64)$', 'arm64') | regex_replace('^(x86_64)$', 'amd64') }} signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present
        filename: docker
        mode: "0644"

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Create filesystem on EBS volume
      community.general.filesystem:
        fstype: xfs
        dev: /dev/nvme2n1

    - name: Create mount point
      ansible.builtin.file:
        path: /mnt/reth_data
        state: directory
        mode: "0755"

    - name: Mount EBS volume
      ansible.posix.mount:
        path: /mnt/reth_data
        src: /dev/nvme2n1
        fstype: xfs
        opts: "defaults"
        state: mounted
